/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.unipar.onlinewallet.View;

import br.com.unipar.onlinewallet.Controller.ClassShare;
import br.com.unipar.onlinewallet.Controller.ConnectionCon;
import br.com.unipar.onlinewallet.Controller.PeopleRegister;
import br.com.unipar.onlinewallet.Models.People;
import java.awt.event.WindowEvent;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.sql.Connection;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matheus
 */
public class ScreenUser extends javax.swing.JInternalFrame {

    Connection conn;
    int family;
    public int I;
    /**;
     * Creates new form ScreenUser
     */
    public ScreenUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        View = new javax.swing.JPanel();
        Cancel = new javax.swing.JButton();
        DeleteUser = new javax.swing.JButton();
        NewUser = new javax.swing.JButton();
        ChangeUser = new javax.swing.JButton();
        RefreshUser = new javax.swing.JButton();
        Panelnav = new javax.swing.JScrollPane();
        tbReg = new javax.swing.JTable();
        Register = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Person = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TxtCPF = new javax.swing.JFormattedTextField();
        TxtBornDate = new javax.swing.JFormattedTextField();
        TxtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LblEstado1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CbxSex = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        Rbfather = new javax.swing.JRadioButton();
        RbMother = new javax.swing.JRadioButton();
        RbSon = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        TxtEmissao = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtRG = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        BtnSave = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TxtRoad = new javax.swing.JTextField();
        LblNumber = new javax.swing.JLabel();
        TxtNumber = new javax.swing.JTextField();
        lBLDisctrict = new javax.swing.JLabel();
        TxtCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LblEstado = new javax.swing.JLabel();
        CbxCountry = new javax.swing.JComboBox();
        LblNumber1 = new javax.swing.JLabel();
        LblRoad = new javax.swing.JLabel();
        TxtCEP = new javax.swing.JFormattedTextField();
        txtDistrict = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LblTelephone = new javax.swing.JLabel();
        TxtTelephone = new javax.swing.JFormattedTextField();
        javax.swing.JLabel LblEmail = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(1030, 549));
        setMinimumSize(new java.awt.Dimension(1030, 549));
        setNormalBounds(new java.awt.Rectangle(0, 0, 1030, 549));
        setPreferredSize(new java.awt.Dimension(1030, 549));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 535));

        View.setMaximumSize(new java.awt.Dimension(1030, 549));
        View.setMinimumSize(new java.awt.Dimension(1030, 549));
        View.setPreferredSize(new java.awt.Dimension(1000, 535));

        Cancel.setText("Cancelar");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        DeleteUser.setText("Deletar");
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });

        NewUser.setText("Novo");
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });

        ChangeUser.setText("Alterar");
        ChangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeUserActionPerformed(evt);
            }
        });

        RefreshUser.setText("Atualizar");
        RefreshUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshUserActionPerformed(evt);
            }
        });

        Panelnav.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tbReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Cpf/Cnpj", "Rua", "Número", "Bairro", "Cidade", "Estado", "Email", "Telephone", "DataNascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbReg.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbReg.setMaximumSize(new java.awt.Dimension(705, 80));
        tbReg.setMinimumSize(new java.awt.Dimension(500, 80));
        tbReg.setName(""); // NOI18N
        Panelnav.setViewportView(tbReg);
        if (tbReg.getColumnModel().getColumnCount() > 0) {
            tbReg.getColumnModel().getColumn(0).setResizable(false);
            tbReg.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbReg.getColumnModel().getColumn(1).setPreferredWidth(260);
            tbReg.getColumnModel().getColumn(2).setResizable(false);
            tbReg.getColumnModel().getColumn(2).setPreferredWidth(200);
            tbReg.getColumnModel().getColumn(3).setPreferredWidth(260);
            tbReg.getColumnModel().getColumn(4).setResizable(false);
            tbReg.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbReg.getColumnModel().getColumn(5).setPreferredWidth(260);
            tbReg.getColumnModel().getColumn(6).setPreferredWidth(260);
            tbReg.getColumnModel().getColumn(7).setResizable(false);
            tbReg.getColumnModel().getColumn(7).setPreferredWidth(60);
            tbReg.getColumnModel().getColumn(8).setPreferredWidth(260);
            tbReg.getColumnModel().getColumn(9).setResizable(false);
            tbReg.getColumnModel().getColumn(9).setPreferredWidth(200);
        }

        javax.swing.GroupLayout ViewLayout = new javax.swing.GroupLayout(View);
        View.setLayout(ViewLayout);
        ViewLayout.setHorizontalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChangeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(NewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RefreshUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Panelnav, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        ViewLayout.setVerticalGroup(
            ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panelnav, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(ViewLayout.createSequentialGroup()
                        .addComponent(RefreshUser)
                        .addGap(18, 18, 18)
                        .addComponent(NewUser)
                        .addGap(18, 18, 18)
                        .addComponent(ChangeUser)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteUser)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel)
                        .addGap(0, 341, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Register.setEnabled(false);
        Register.setMaximumSize(new java.awt.Dimension(1000, 535));
        Register.setMinimumSize(new java.awt.Dimension(1000, 535));
        Register.setPreferredSize(new java.awt.Dimension(1000, 535));

        Person.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLabel6.setText("Data Nasc.");

        try {
            TxtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TxtBornDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtBornDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBornDateActionPerformed(evt);
            }
        });

        TxtName.setToolTipText("");

        jLabel1.setText("Nome");

        LblEstado1.setText("Sexo");
        LblEstado1.setToolTipText("");

        jLabel5.setText("Cpf");

        CbxSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        CbxSex.setSelectedIndex(-1);
        CbxSex.setToolTipText("");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Membro"));

        Rbfather.setSelected(true);
        Rbfather.setText("Pai");
        Rbfather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbfatherActionPerformed(evt);
            }
        });

        RbMother.setText("Mãe");
        RbMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbMotherActionPerformed(evt);
            }
        });

        RbSon.setText("Filho(a)");
        RbSon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbSonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Rbfather)
                .addGap(25, 25, 25)
                .addComponent(RbMother)
                .addGap(18, 18, 18)
                .addComponent(RbSon)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(Rbfather)
                .addComponent(RbMother)
                .addComponent(RbSon))
        );

        jLabel8.setText("Data emissão:");

        try {
            TxtEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmissaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Rg");

        try {
            TxtRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout PersonLayout = new javax.swing.GroupLayout(Person);
        Person.setLayout(PersonLayout);
        PersonLayout.setHorizontalGroup(
            PersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblEstado1)
                        .addGap(18, 18, 18)
                        .addComponent(CbxSex, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PersonLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBornDate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PersonLayout.setVerticalGroup(
            PersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(TxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblEstado1)
                    .addComponent(CbxSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(TxtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(TxtEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(TxtBornDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Person, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Person, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BtnSave.setText("Gravar");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancelar");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        jPanel1.setName("Location"); // NOI18N

        LblNumber.setText("Número");

        TxtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumberActionPerformed(evt);
            }
        });

        lBLDisctrict.setText("Bairro");
        lBLDisctrict.setToolTipText("");

        jLabel9.setText("Cidade");

        LblEstado.setText("Estado");
        LblEstado.setToolTipText("");

        CbxCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "TO", "DF" }));
        CbxCountry.setSelectedIndex(-1);
        CbxCountry.setToolTipText("");

        LblNumber1.setText("CEP");

        LblRoad.setText("Rua");
        LblRoad.setToolTipText("");

        try {
            TxtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistrictActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblRoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtRoad, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lBLDisctrict)
                        .addGap(18, 18, 18)
                        .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblNumber1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(TxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblRoad)
                    .addComponent(LblNumber)
                    .addComponent(TxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lBLDisctrict)
                    .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(LblEstado)
                    .addComponent(CbxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNumber1)
                    .addComponent(TxtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contato"));

        LblTelephone.setText("Telefone");
        LblTelephone.setToolTipText("");

        try {
            TxtTelephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        LblEmail.setText("Email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTelephone)
                .addGap(18, 18, 18)
                .addComponent(TxtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTelephone)
                    .addComponent(LblEmail)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register);
        Register.setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(RegisterLayout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(BtnSave)
                        .addGap(49, 49, 49)
                        .addComponent(BtnCancel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1038, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(View, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(View, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1050, 535);
    }// </editor-fold>//GEN-END:initComponents
    void windowActivated(WindowEvent e){
        Register.setVisible(false);  
    }
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
            this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        People people = new People();
        people.setId((Long) Long.parseLong(tbReg.getValueAt(tbReg.getSelectedRow(), 0).toString()));
        ClassShare ClassShare = new ClassShare();
        ClassShare.remove("ID", "PEOPLE", people.getId().toString());
        RefreshUserActionPerformed(evt);
    }//GEN-LAST:event_DeleteUserActionPerformed

    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed
        TxtBornDate.setText("");
        TxtCEP.setText("");
        TxtCPF.setText("");
        TxtRoad.setText("");
        TxtTelephone.setText("");
        TxtNumber.setText("");
        TxtEmail.setText("");
        TxtCity.setText("");
        txtDistrict.setText("");
        CbxSex.setSelectedIndex(-1);
        RbfatherActionPerformed(evt);
        TxtEmissao.setText("");
        CbxCountry.setSelectedIndex(-1);
        TxtRG.setText("");
        TxtName.setText("");
        View.setVisible(false);
        Register.setVisible(true);

    }//GEN-LAST:event_NewUserActionPerformed

    private void ChangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeUserActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
       ScreenUserRegister ScreenRegister = new ScreenUserRegister();
       ScreenRegister.setVisible(true);
    }//GEN-LAST:event_formInternalFrameActivated

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        People people = new People();
        PeopleRegister reg = new PeopleRegister();
        try {
        people.setBirthDate(TxtBornDate.getText());
        people.setZipCode(TxtCEP.getText());
        people.setCpf(TxtCPF.getText());
        people.setRoad(TxtRoad.getText());
        people.setTelephone(TxtTelephone.getText());
        people.setNumber(Integer.parseInt(TxtNumber.getText()));
        people.setEmail(TxtEmail.getText());
        people.setCity(TxtCity.getText());
        people.setDistrict(txtDistrict.getText());
        people.setSex(CbxSex.getSelectedItem().toString());
        people.setState(CbxCountry.getSelectedItem().toString());
        people.setRg(TxtRG.getText());
        people.setName(TxtName.getText());
        reg.save(people);
        View.setVisible(true);
        Register.setVisible(false);    
        } catch (Exception ex) {
            Logger.getLogger(ScreenUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        View.setVisible(true);
        Register.setVisible(false);
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void TxtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumberActionPerformed

    private void RbfatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbfatherActionPerformed
       if (Rbfather.isSelected()){
        family = 0; 
        RbMother.setSelected(false);
        RbSon.setSelected(false);
       }
    }//GEN-LAST:event_RbfatherActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Register.setVisible(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void RefreshUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshUserActionPerformed
       
       try {
            //Atualizar a tabela de usuáriop
            ClassShare ClassShare = new ClassShare();
            ResultSet RS = ClassShare.findAll("Person");
            DefaultTableModel modelo = (DefaultTableModel) ScreenUser.tbReg.getModel();
            modelo.setNumRows(0);
            int columns = RS.getMetaData().getColumnCount();
            while (RS.next()) {
                Object[] row = new Object[columns];
                for(I = 0; I < columns; I++){
                    row[I-1]= RS.getObject(I);
                } 
                ((DefaultTableModel)tbReg.getModel()).insertRow(RS.getRow()-1, row);
            }
       }catch (SQLException ex) { 
                 
                 }                 
    }//GEN-LAST:event_RefreshUserActionPerformed
    private void TxtBornDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBornDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBornDateActionPerformed

    private void RbMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbMotherActionPerformed
       if (RbMother.isSelected()){
           family = 1; 
            Rbfather.setSelected(false);
            RbSon.setSelected(false);
        }
    }//GEN-LAST:event_RbMotherActionPerformed

    private void RbSonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbSonActionPerformed
        if (RbSon.isSelected()){
            family = 2; 
            Rbfather.setSelected(false);
            RbMother.setSelected(false);
        }
    }//GEN-LAST:event_RbSonActionPerformed

    private void TxtEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmissaoActionPerformed

    private void txtDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistrictActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistrictActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton Cancel;
    private javax.swing.JComboBox CbxCountry;
    private javax.swing.JComboBox CbxSex;
    private javax.swing.JButton ChangeUser;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JLabel LblEstado;
    private javax.swing.JLabel LblEstado1;
    private javax.swing.JLabel LblNumber;
    private javax.swing.JLabel LblNumber1;
    private javax.swing.JLabel LblRoad;
    private javax.swing.JLabel LblTelephone;
    private javax.swing.JButton NewUser;
    private javax.swing.JScrollPane Panelnav;
    private javax.swing.JPanel Person;
    private javax.swing.JRadioButton RbMother;
    private javax.swing.JRadioButton RbSon;
    private javax.swing.JRadioButton Rbfather;
    private javax.swing.JButton RefreshUser;
    private javax.swing.JPanel Register;
    private javax.swing.JFormattedTextField TxtBornDate;
    private javax.swing.JFormattedTextField TxtCEP;
    private javax.swing.JFormattedTextField TxtCPF;
    private javax.swing.JTextField TxtCity;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JFormattedTextField TxtEmissao;
    private javax.swing.JTextField TxtName;
    private javax.swing.JTextField TxtNumber;
    private javax.swing.JFormattedTextField TxtRG;
    private javax.swing.JTextField TxtRoad;
    private javax.swing.JFormattedTextField TxtTelephone;
    private javax.swing.JPanel View;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lBLDisctrict;
    public static javax.swing.JTable tbReg;
    private javax.swing.JTextField txtDistrict;
    // End of variables declaration//GEN-END:variables
}
